# 1.3. Do other studies by the research team highlight causes for concern?

```{r}
#| include: false
if(file.exists("../_setup.R")){source("../_setup.R")}
```

We suggest the reviewer searches the first, corresponding, and last author (at minimum) on the [Retraction Watch database](http://retractiondatabase.org/).

It can be helpful to repeat the search with first names and last names switched, because journals and publishers may transpose names.

A track record of problems relating to trustworthiness may introduce doubts about the index study.

The reviewer should pay close attention to the content of any notices associated with the author. For example, a previous retraction due to an honest error may not warrant any concerns based on the author's track record.

If the reviewer does perform these searches in relation to middle authors, the reviewer should consider whether a track record of integrity problems relating to middle authors on the index study are sufficient to introduce concerns about the trustworthiness of the index study. The reviewer should consider the contribution statement in the manuscript to assist with this decision.

If comments relating to integrity issues on other studies from the author team are identified in other locations, not originating from the journal or publisher (for example, in a letter to the editor or PubPeer) we suggest that the reviewer considers the content of the comment as it may be useful in helping to identify problematic features of the index study.

The answer to this check should contribute to a domain-level judgement.

## Examples

::: {.callout-note title = "Example 1"}
A reviewer performs this check on a trial of a probiotic supplement for gestational diabetes by searching for the first and last author on [http://retractiondatabase.org/](http://retractiondatabase.org/). The search on the last author returns a large number of notices, including numerous retractions and expressions of concern relating to concerns over data integrity. The reviewer reads some of the associated notices to ensure that they are related to data integrity concerns. The reviewer answers "yes" for this check, and this response contributes to the domain-level judgement.
:::

::: {.callout-note title = "Example 2"}
A reviewer performs this check on a trial of a dietary intervention for sleep apnea, by searching for the first and last author on [http://retractiondatabase.org/](http://retractiondatabase.org/). This identifies a publication describing a similar trial conducted concurrently by the author team that has been retracted. The retraction alludes to a lack of transparency on behalf of the authors but is not entirely clear about the motivation for the retraction. The reviewer answers "yes" for this check, and this response contributes to the domain-level judgement.
:::
