# 4.3. Are any baseline data implausible? <span class="badge badge-draft1">✎ Very rough draft</span>

```{r}
#| include: false
if(file.exists("../_setup.R")){source("../_setup.R")}
```

Consider clinical/biological and numerical plausibility of baseline characteristics. Look for unusual patterns such as excess even/odd numbers, multiples of 5, or implausibly identical values across groups.

There are also quantitative methods for the assessment of whether groups are systematically too similar or too different assuming random assignment:

- Barnett's Baseline [Web app](https://aushsi.shinyapps.io/baseline/) and associated R package
- Carlisle's method [URL for implementations?]
- Bolland's reappraised R package [URL needed]

Separately, there are quantitative methods to assess whether a) reported p values and b) effect sizes for between-groups differences for continuous or categorical data can be reproduced from reported summary statistics (i.e., M/SD/N or counts):

- recalc [Web app](https://errors.shinyapps.io/recalc_independent_t_test/)
- Bolland's p value recalculator Web app [URL needed]
